### ISSUE TITLE
Complete camera non-linearity correction

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#10]
1) IG to complete acquisition of all camera data at various exposures and digital number (DN) values (SCOTT SEWELL / PHIL)
2) Complete analysis and fitting of data to create pixel-by-pixel correction mapping for each of 4 cameras. (ALFRED)
3) Implement correction in data pipeline.

**Comment by mgalloy** [comment]
Filenames for camera correction need to use epoch or date to account for changes in BITPIX, etc.

**Comment by jburkepile** [comment]
Mike ran images  with NO interpolation (e.g. no distortion, no polarization transformation, no rotation), with and withOUT camera correction. Both sets show a vertical noise pattern indicating one of the ADCs is significantly noiser than the others. The image below was taken on May 23, 2017 at 20:20:55 and has no camera correction. It is zoomed by a factor of 8 to show the vertical ADC pattern. The camera corrected image had the same pattern. The next test is to look at stream data (no LUT applied) to see if there is a problem in the application of the LUTs at Mauna Loa.

![screenshot](https://user-images.githubusercontent.com/18175973/47390870-a0dcc080-d6d5-11e8-904a-11080227b5ea.png)

**Comment by mgalloy** [comment]
I have the 1.0 ms camera correction files for 11461 and 13889 (with correct lookup tables) for 20131106 and 20131203.

**Comment by mgalloy** [comment]
We have camera calibration files for the entire mission.
