### ISSUE TITLE
Adjust GIF scaling over mission

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#104]
- [ ] Adjust cropped and full res pB GIFs for solar cycle changes.
- [ ] Adjust quicklook GIF for solar cycle changes and hardware changes. Fix changes due to 2nd lyot stop and camera performance by changing value of `imax` in the quality program to `imax/2.0` for this epoch:
    - Jan 15, 2016 through May 21, 2017: `imax = max(pb0s/2.0)`
    - New cameras installed on May 22, 2017 and `imax` can be changed back to `imax = max(pb0s)`

**Comment by mgalloy** [comment]
Added in 5113817928a5674d63529548f19d244bf20189d9.

**Comment by jburkepile** [comment]
In the attached excel spreadsheet, I have documented the gif scaling I selected for full res and cropped pB over the mission and included the days I used to derive that scaling. I have opted to maximize contrast where S/N is good while minimizing saturation in the inner corona. The result is images that have good quality but they are not useful for viewing very faint structures in the outer FOV. NRGF images should be used for that purpose. ... J. Burkepile
[KCor_pb_gif_scaling.xlsx](https://github.com/NCAR/kcor-pipeline/files/4846599/KCor_pb_gif_scaling.xlsx)
Some examples of the gif scaling are provided below.
![20131210_202810_kcor_l1 5_crop](https://user-images.githubusercontent.com/18175973/86028512-31ad8880-b9ef-11ea-976b-f1c8e619da4c.gif)
![20131210_202810_kcor_l1 5_fullres](https://user-images.githubusercontent.com/18175973/86028577-4722b280-b9ef-11ea-9ef4-7635a5cdcbdd.gif)
![20150514_174017_kcor_l1 5_crop](https://user-images.githubusercontent.com/18175973/86028721-7cc79b80-b9ef-11ea-8913-8c456a0ffb32.gif)
![20150514_174017_kcor_l1 5_fullres](https://user-images.githubusercontent.com/18175973/86028754-84874000-b9ef-11ea-96a6-e03cdcb05677.gif)
![20160702_195544_kcor_l1 5_crop](https://user-images.githubusercontent.com/18175973/86028770-89e48a80-b9ef-11ea-82e5-a6aaba6c4d14.gif)
![20160702_195544_kcor_l1 5_fullres](https://user-images.githubusercontent.com/18175973/86028781-8e10a800-b9ef-11ea-8b35-a8c62f5ce5af.gif)
![20181101_175740_kcor_l1 5_fullres](https://user-images.githubusercontent.com/18175973/86028791-910b9880-b9ef-11ea-82ac-06669e69c630.gif)
![20181101_175740_kcor_l1 5_crop](https://user-images.githubusercontent.com/18175973/86028805-9832a680-b9ef-11ea-9a6c-2bca17bb562b.gif)
![20200120_193841_kcor_l1 5_crop](https://user-images.githubusercontent.com/18175973/86028819-9c5ec400-b9ef-11ea-9203-19af279f46ca.gif)
![20200120_193841_kcor_l1 5_fullres](https://user-images.githubusercontent.com/18175973/86028830-9ff24b00-b9ef-11ea-85bf-53a5aa0a4e21.gif)

**Comment by jburkepile** [comment]
Closing ticket.  Will verify gif scalings over the mission look okay as Mike reprocesses.
