### ISSUE TITLE
Refine level0 quality control for 32-bit data early in mission

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#106]
Add `if` statement in KCor level 0 quality program to cloud check:
- If `bitpix` of image = 16 then `cmin` = 200.0 & `cmax` = 2200.
- If `bitpix` of image = 32 then `cmin` = 3.e5 & `cmax` = 4.29e09

**Comment by mgalloy** [comment]
Current `cmin` and `cmax` values are in the `epochs.cfg` file:

    [20130930.084301]
    cmin                           : 200.0
    cmax                           : 5.0e7

    [20131113.064240]
    cmin                           : 10.0
    cmax                           : 2200.0

    [20131122.093243]
    cmin                           : 20.0

    [20131123.083029]
    cmin                           : 30.0

    [20131204.082148]
    cmin                           : 200.0

**Comment by mgalloy** [comment]
Need to check 2013 reprocessed data for 10/1, 10/4, and 10/25.
