### ISSUE TITLE
Daily engineering and science plots in eod processing

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#116]
1) Alter existing daily plot of radial intensity:

   - [x] add plot axis to all 4 sides of plot
   - [x] change title to: "Azimuthally Averaged Radial pB Intensity for yyyymmdd @  hhmmss UT"
   - [x] add label to indicate the dotted lines are standard deviation of radial average

2) Change y-axis scaling of `YYYYMMDD.kcor ocen.gif` plot in `kcor_plotcenters.pro` to accommodate changes to camera positions over mission. At time of writing, need to include 3 epochs:

   - [x] Sept 30, 2013 thru June 18, 2015: Use current values: `yrange = [480., 540.]`
   - [x] June 19, 2015 thru May 21, 2017: `yrange = [505., 535.]`
   - [x] May 22, 2017 thru present: `yrange = [490,525.]`

3) Create new daily GIF plot of sky transmission correction (FITS keyword = SKYTRANS) vs. time over day. Please set `yrange = [0.80, 1.20]`. We need to flag `SKYTRANS` values outside of this range as errors in the log.

4) Create plots of average pB at 4 fixed heights vs. time over observing day. Please generate 1 plot per height. You can stack 2 plots in the same file. 

   For all plots: use linear scales; delta angle = 0.3 degree;  thickness = +/- 0.005 R_sun

   Heights: 

       1.11 Rsun    yrange = [1.e-07, 7.3-07] 
       1.3 Rsun     yrange = [6.e-08, 3.e-07]
       1.5 Rsun     yrange = [5.e-09, 1.2e-07]
       1.8 Rsun     yrange = [1.e-09, 4.e-08]

   An example of a single plot from Mk4 is shown below.

   ![20040202 mk4 pb r1 5](https://user-images.githubusercontent.com/18175973/61470960-2c227400-a93f-11e9-93b6-536411630fb9.gif)

**Comment by mgalloy** [comment]
### Med/median images

- [ ] scale L0 `l0.{med,mean}{cols,rows}.cam{0,1}.gif` appropriately for 32-bit data (use epoch file)

### Sky trans plot

- [ ] change title of `kcor.skytrans.gif` to "Sky transmission correction", filename to `kcor.skytrans-correct.gif', `YTITLE` to "Sky trans @ flat image / Sky trans @ science image"
- [ ] plot with a symbol "+" (not a dot)

### Engineering plot

- [ ] add to title of DIM plot "(Sky transmission)"
- [ ] add "Relative sky transmission" to SGS DIM plot `YTITLE`
- [ ] plot with a symbol "+" (not a dot)

### Mean pB plots

- [ ] change y-axis scale on 1.30 R_sun plot to `[3.0e-8, 3.0e-7]`
- [ ] plot with a symbol "+" (not a dot)
