### ISSUE TITLE
Do not create quicklook GIFs with rotated images

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#118]
Currently, quicklook GIFs are shifted to array center, obscuring any relative motion of the occulter over the day. For examples: 20190612, 20190712.

Engineering plots (`YYYY.MM.DD.kcor.ocen.gif`) show 7 to 8 pixel drift in x-component of cameras over long observing day. This motion is not visible in quicklooks since images have been shifted to the center of array.

Fix:  make GIF with unshifted pb0 image:

- [x] shift mask to match center of pb0 image, i.e., `xcen`, `ycen`
- [x] apply mask: `pb0 = pb0 * shifted mask`
- [x] scale and dislay masked unshifted image
- [x] change `tvcircle` centers from `axcen`, `aycen` to `xcen`, `ycen`
- [x] display "NORTH" in the correction location with the correction orientation

**Comment by mgalloy** [comment]
I am not 100% sure that the "NORTH" is placed in the correction location.

**Comment by mgalloy** [comment]
@jburkepile checked dates `20190812`, `20190815`, and `20150501` and everything looks good.
