### ISSUE TITLE
Compute SKYTRANS from fit to SGS DIMV data for cal epoch version 1 and 2

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#120]
SGS data are erratic early in mission. Compute `SKYTRANS` correction using fits to SGS data on 'good' days for Epoch 1 and Epoch 2:

Epoch 1: 20130930.084301 to 20131004.083634  [HST]

- Compute `SKYTRANS` using coefficients of 2nd order polynomial fit:  -44.3089    5.32937   -0.133604
- Change `SKYTRANS` FITS comment to:  "sky transmis.correct. from fit to 10/1/13 DIMV"

I used 2nd order polynomial since there are fewer than 3 hours of good data.
![2013oct01_sgsdimv_fit2](https://user-images.githubusercontent.com/18175973/61418132-c7bbd200-a8b6-11e9-9fe1-ce4f69bb6e50.gif)

Epoch 2: 20131004.083635 to 20131111.081541 [HST]

- Compute `SKYTRANS` using coefficients of 5th order fit:  -1153.75,  249.800,  -21.4071,  0.914107,  -0.0194243,  0.000164027
- Change `SKYTRANS` FITS comment to:  "sky transmis.correct. from fit to 11/1/13 DIMV"

![2013nov01_sgsdimv_fit5](https://user-images.githubusercontent.com/18175973/61416132-ea96b800-a8af-11e9-94a8-9f17196946bd.gif)

Other notes:

- Continue to record actual SGS data values into database and fits headers. 
- Need to edit  'use_sgs' = YES/NO in epoch file.

**Comment by mgalloy** [comment]
@jburkepile OKs results from running on 20130930, 20131001, 20131004, 20131005, and 20131015.
