### ISSUE TITLE
Verify with Alfred should we subtract the dark in the eod calibration

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#131]
Both the flat and dark have the camera correction, should the gain also have the dark subtracted?

**Comment by dwijn** [comment]
Did this get resolved? All data, regardless of its purpose, needs to have the camera correction applied first. Once that is done, science data should be corrected with the flat and dark: data_corrected = (data - dark) / (flat - dark)

**Comment by mgalloy** [comment]
I'm trying to remember exactly what the worry was when I opened this ticket.

It looks like the dark is subtracted from the gain in this line (line 179 right now) of `kcor_reduce_calibration_read`:

    gain = (clear / float(gotclear) - dark) / idiff

This gain is what is stored in the cal netCDF. So the science images can divide by the gain that is stored in the cal netCDF file and it should be fine.

**Comment by mgalloy** [comment]
We do not subtract the dark from the gain in the L1 processing.
