### ISSUE TITLE
Recalibrate the transmission of the Light Shaping Diffuser

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#145]
We originally compared the diffuser data to the Mk4 opal data, but this was before Alfred corrected the calibration code. It now appears that with the camera correction code the diffuser data is too dark, so the original estimate of the transmission is too low.

**Comment by jburkepile** [comment]
Recap:
 **The original study to find the transmission of the LSD remians valid.**  No further work is needed on this ticket.

In 2020, Mike recalibrated most of the 2013 data with the revised camera corrections from Alfred. 
Unfortunately, no camera non-linearity correction could be made for the early mission low exposure data taken up until Nov 21, 2013 while the LSD was in use. The signal-to-noise of the camera data was too low.  The lack of a camera correction for these early data is the most likely culprit for the low intensities as compared with the recalibrated opal data that have longer exposures and a proper camera non-linearity correction.  An additional study was made to estimate a simple camera correction for the early mission. That work  is reported in the ticket  'Generate ad hoc camera correction for early mission  #211

I have attached a report (that is also attached in ticket #211),  showing the method and results of the LSD study and the work to obtain an ad-hoc camera correction for the early mission.

I am closing this ticket.

[Transmission_of_Light_Shaping_Diffuser_and_ad-hoc_camera_correction.docx](https://github.com/NCAR/kcor-pipeline/files/6155514/Transmission_of_Light_Shaping_Diffuser_and_ad-hoc_camera_correction.docx)
