### ISSUE TITLE
Apply Gaussian smoothing to the sky image in sky polarization removal

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#147]
In the sky polarization removal, the sky image (`qmk4`) should be smoothed like:

    smoothed_qmk4 = gauss_smooth(qmk4, 3, /edge_truncate)

We need to be careful when changing the steep gradients in the inner corona.

**Comment by mgalloy** [comment]
4a4da124e246690a257fd16970fdc57cf351734a adds config file option to do this.

**Comment by mgalloy** [comment]
For comparison, these two runs for 20200421 are identical except one was done using a gaussian smoothing of the sky and one was not:

    /hao/sunset/Data/KCor/raw.smoothsky/20200421
    /hao/sunset/Data/KCor/raw.nosmoothsky/20200421

**Comment by mgalloy** [comment]
Reprocessing 20200421 in the `.fill` directory on sunset.

**Comment by jburkepile** [comment]
I (Joan) neglected to verify that sky smoothing was turned on for KCor reprocessing. I asked Mike to turn it 'ON'  on Feb 9, 2022. Some of the 2021 data and all the 2022 data will have sky smoothing. Check level 2 fits keyword 'SKYSM' to see if sky smoothing was turned on. If the keyword is not present then sky smoothing was off.
All data processed on and after Feb 9, 2022 will have sky smoothing turned ON.

**Comment by mgalloy** [comment]
Sky smoothing was turned on via config file for all production config files as of 1 minute ago.
