### ISSUE TITLE
Add epochs in early mission for using only a single camera

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#158]
In the `epochs.cfg` file, the `cameras` value should be "0" for certain time periods.

**Comment by jburkepile** [comment]
Checked early mission data (Oct-Nov 2013). There are a few days such as Oct 5, 2013 where camera 0 shows a little more noise than camera 1 but difference in signal between 2 cameras is small. 2 camera combination provides sqrt(2) signal-to-noise improvement and is best path forward. These early mission data have such low exposures there is no camera correction. Almost no coronal signal above ~1.6 Rsun.

Conclusion: Use 2 cameras.
I am closing this ticket.
J. Burkepile
