### ISSUE TITLE
Create new distortion correction for cameras installed in Dec 2019

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#166]
We need to calculate a new distortion for the cameras installed in late 2019, on 20191216. All data after the installation data need to be reprocessed.

- [x] create new distortion(s)
- [x] reprocess data on and after 20191216
- [x] decide between distortion files and update `epochs.cfg`

**Comment by mgalloy** [comment]
Results for `20191224` for both candidate distortion files are in:

    /hao/sunset/Data/KCor/raw.{210743,212805}

**Comment by jburkepile** [comment]
After final alignment of new cameras on 20191216, Ben ran 2 distortion tests, one with the grid in focus and one with the cameras in focus. The results were similar but the test with the camera in focus showed better overall alignment of the grid in the 2 cameras. 
![20191216_212805_distortion_beam1_minus_beam2](https://user-images.githubusercontent.com/18175973/80034819-3ebc7180-84ac-11ea-9543-ca304eb616e3.GIF)
