### ISSUE TITLE
Shift camera correction for epochs

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#171]
Beginning on 20191209, a horizontal shift in the camera correction is necessary to maintain the smoothness of the raw values. After 20200102, a 2-pixel shift in the image corrects the gain to produce a smooth profile. On 20191228, a 2-pixel shift corrects camera 0, but not camera 1. Determine the correct shifts necessary in both cameras, by date.

- [x] move `xshift_camera_correctection` from config file to epochs file
- [x] make `xshift_camera_correctection` a two-element floating point array
- [x] add FITS keyword documenting shift applied `XCAMSHFT`, comment  " [px] cam corr shift to align w/ img, + to left"
- [x] add necessary epochs for `xshift_camera_correction`

**Comment by alicehao** [comment]
The camera data is retrieved from a pointer that is provided by the camera software, CirHandle.pBufData:
    Sbuf  = (unsigned short *)CirHandle.pBufData;
I have not changed the socketcam code for a very long time, so I don't think the problem
lies there.

I do see an old email that new bitflow drivers and new photonfocus drivers were installed around Oct 2019.
It is possible that one of these drivers might be at fault.  Alfred really knows cameras and may be able to comment.

**Comment by bberkeyU** [comment]
In some email exchange with Bitflow it looks like the driver change from Bitflow SDK 5.3 to 6.3 there as a change in the firmware that changed the acquisition timing so they sent us new .r64 camera config files to try out.

**Comment by mgalloy** [comment]
Here are the gains that at least some non-smoothness:

  - 20131221 (cam 1)
  - 20140528-20140603 (cam 0)
  - 20140804 (both)
  - 20141007 (both)
  - 20150320-20150323 (both)
  - 20150602 (cam 0)
  - 20150718 (cam 1)
  - 20151213 (cam 1)
  - 20151217 (cam 1)
  - 20160503 (cam 0)
  - 20170405 (cam 0)
  - 20170522- (not fully smooth in cam 0)
  - 20170622 (cam 1)
  - 20190315 (cam 0)
  - 20190508 (cam 1)
  - 20190620 (cam 1)
  - 20190808 (cam 1)
  - 20191023 (cam 1)
  - 20191209-20200615 (both, we know about these already and can fix)

The plots are in:

  /hao/sunset/Data/KCor/gain-profiles

**Comment by mgalloy** [comment]
Here is a profile of the gain for 20170522, when cam0 becomes less smooth than normal, i.e., cam1 in this example:

![20170522_210649_kcor_cal_v12_2 0 1_2 500ms ncdf-profile](https://user-images.githubusercontent.com/713524/88594333-3d0bc800-d01e-11ea-8561-9bfcc847b690.png)

**Comment by mgalloy** [comment]
What we still need are the epoch xshift values for:

- [ ] 20131221 (cam 1)
- [ ] 20140528-20140603 (cam 0)
- [ ] 20140804 (both)
- [ ] 20141007 (both)
- [ ] 20150320-20150323 (both)
- [ ] 20150602 (cam 0)
- [ ] 20150718 (cam 1)
- [ ] 20151213 (cam 1)
- [ ] 20151217 (cam 1)
- [ ] 20160503 (cam 0)
- [ ] 20170405 (cam 0)
- [ ] 20170622 (cam 1)
- [ ] 20190315 (cam 0)
- [ ] 20190508 (cam 1)
- [ ] 20190620 (cam 1)
- [ ] 20190808 (cam 1)
- [ ] 20191023 (cam 1)

**Comment by mgalloy** [comment]
I am not getting smooth gain profiles for any of the new epochs (with 16 pixel either left or right).

**Comment by mgalloy** [comment]
I did some exhaustive testing of various xshift values for 20170622.

For camera 0 (already smooth), the std dev / median is about 0.0164 at the correct xshift value. Moving away from that value, increases to about 0.0279 in the region of about 24 pixels shifted left or right from the optimal. After 24 pixels away from the optimal shift, the std dev / median value increases to about 0.05 30 pixels away from optimal. (See attached file for exact values.)

For camera 1 (not smooth), xshift=16 is in the middle of the region where std dev / median is minimized, but never reaches a smooth value for any value tried. (See attached file for exact values.)

Conclusion: the averaged gain for 20170622 cannot be smoothed by shifting it in the x-direction.

Caveats with this analysis:
- Not shifting individual frames, only averaged raw FITS files.
- Shifting all raw FITS files by the same amount. There are 7 darks and 2 clears that are used for this calculation and it is possible that there are different shifts required for each one (or portion of one).
- A similar analysis using y-direction shifts also did not smooth the gain.

[20170622-xshift-search.txt](https://github.com/NCAR/kcor-pipeline/files/5308081/20170622-xshift-search.txt)

**Comment by mgalloy** [comment]
I think there is a shift in camera 0 for 20210412.

**Comment by jburkepile** [comment]
Fix column shift in **camera 1 only**. See picture below epoch that illustrates **8 extra columns on right side of image**
EPOCH: 20220303  07:46:01 HST   Camera 1 only 8 columns on right side need to be shifted to left side

EPOCH: 20220303  09:20:53 HST  No shifting needed. Back to normal
![test](https://user-images.githubusercontent.com/18175973/158269712-b931ee68-ad11-41b5-b667-512c7e37242b.png)

**Comment by jburkepile** [comment]
The shift correction for March 3 data looks good. 
This ticket can be closed.
