### ISSUE TITLE
Gallery quicklooks

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#173]
- [x] Make a new cropped (512x512, in the manner of the NRGF quicklooks) quicklook for observers to use in an animation.
- [x] Distribute the cropped quicklooks to the gallery.
- [x] Put the full name of the quality level in the annotations of all quicklooks.

**Comment by alicehao** [comment]
Hi Mike,
there are existing kcor and gong quicklooks that are created at MLSO and then ldm'ed to HAO
that then end up in the realtime displays that are shown on the 3rd floor computer.
Don uses the gong images and AIA images (AIA's are created at HAO) to the realtime
displays on the mesa and on the displays by the elevator.   If you need my help to insure these
various data paths don't break with the changes you are making, feel free to ask.

**Comment by bberkeyU** [comment]
Hi Mike,

I think we can remove the requirement to make a copy to Gallery.  I have a some new animation code that seems to work pretty well when pointing directly at the kcor pipeline data directories.  

I would like to see a slightly different color pallet and/or change in intensity levels on the quicklook gives.  The gray on black doesn't seem to pack enough contrast on my monitors.


-Ben

**Comment by mgalloy** [comment]
@bberkeyU Without access to your monitor, I think the best process is to give you an IDL routine that given a raw image file and some display parameters, would let you create a quicklook image. Then you can play around with the display parameters until you get something that looks good, at which point I could then use those parameters in the pipeline code. Does this sound reasonable?

**Comment by mgalloy** [comment]
@bberkeyU To use the quicklook display routine:
- make sure to update to the newest version of master (let me know if you need instructions for this)
- make sure at least the `ssw`, `analysis`, `lib`, and `src` are in your `!path` for IDL
- do the following command in IDL:

      IDL> kcor_display_quicklook, l0_filename

There are options to `KCOR_DISPLAY_QUICKLOOK` to control the display; see its documentation for the options you can change:

    ;+
    ; Display quicklook images for both cameras of a raw file.
    ;
    ; :Params:
    ;   l0_filename : in, required, type=string
    ;     filename of a raw KCor file
    ;
    ; :Keywords:
    ;   minimum : in, optional, type=float, default=-10.0
    ;     minimum to use for display
    ;   maximum : in, optional, type=float
    ;     maximum to use for display, default is maximum of annulus values by camera
    ;   exponent : in, optional, type=float, default=0.7
    ;     exponent to use for display
    ;   gamma : in, optional, type=float, default=0.6
    ;     gamma to use for display
    ;   colortable : in, optional, type=integer, default=0
    ;     colortable number 0-74 as passed to `LOADCT`, default is 0 (black/white)
    ;-

For example, you might want to try:

    IDL> kcor_display_quicklook, l0_filename, minimum=0.0, exponent=0.8, colortable=74

**Comment by bberkeyU** [comment]
It is hard to tell what the best answer is.  It seems like the other observers want to see structure in the brightest part of the corona; but I think I would prefer to see the fainter signals and allow the k in the corona; but I would rather pick out fainter things allowing the the inner corona to be washed out.
Ben values:
min=0
max=250
colortable=1
gamma=.2
exponent=.9

Other observer values:
min=-20
max=200
colortable=1
gamma=.5
exponent=.7

Let's use the other observer values.
