### ISSUE TITLE
Daily and long term O1 focus engineering plot

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#174]
The end-of-day KCor pipeline should create two plots: 
1. a daily plot of the `O1FOCS` keyword value vs. observing time
2. a plot of the `O1FOCS` vs observing time of day over the past month

PLOT characteristics:
- plots should have a fixed x-axis range from 16:30 to 03:30 UT or 6:30 to 17:30 HST, whatever is easier.
- plots should have fixed y-axis range from 130 to 140 millimeters

NOTE: early in 2013 @mgalloy found that the `O1FOCS` values are very small ~5 mm, but this is the period during which the FITS headers are unreliable. We will not worry about accommodating this range of data.

**Comment by mgalloy** [comment]
Example of the daily O1 focus plot from dd6f3ec.

![20200813 kcor daily o1focus](https://user-images.githubusercontent.com/713524/90279714-f217f000-de26-11ea-999e-1f1850a6f046.gif)

**Comment by mgalloy** [comment]
Example of the rolling 28 day O1 focus plot from c62e572.

![20200813 kcor 28day o1focus](https://user-images.githubusercontent.com/713524/90282895-64d79a00-de2c-11ea-88ec-1da533436742.gif)
