### ISSUE TITLE
Facility for observers to remove bad calibrations from the real time pipeline.

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/kcor-pipeline#183]
Is there a way for the observers to easily and safely remove bad calibrations from the real time pipeline?    The current scheme works pretty well if Mike is available;  but giving this power to the observers would let us close the loop on fixing the problem much quicker as the observers inspect the data in real time.

Ideally this process would be be GUI based; but a command line interface would work if it didn't take a lot of steps.   Such as a script that could be executed on moonfish that finds the current calibration file and removes it from the Kcor pipeline.  Where possible I would like to avoid the observer having to know what date the current cal file was taken and the name of the previous one.  But just have the script "pop" the top cal off the queue of calibration files.

**Comment by mgalloy** [comment]
Just move the cal file out of the way in:

    kodiak:/export/data1/Data/KCor/calib_files

For example, today I did the following on kodiak:

    $ cd /export/data1/Data/KCor/calib_files
    $ mv 20200920_190210_kcor_cal_v23_2.0.22_2.500ms.ncdf{,.bad}

Any one in the mlso group should be able to do that. Ben, Lisa, and Marc are in the mlso group.

**Comment by bberkeyU** [comment]
We now have a script on the mountain that will automatically rename the newest .ncdf image in the calib_files directory to be ncdf.bad
