### ISSUE TITLE
Update SGS plots

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#246]
Create more SGS plots similar to the `DIMV` and `SCINT` plot. The plots should be:

- `DIMV`, `DIMS`, and `SCINT` in `YYYYMMDD.kcor.sgs.sky_transmission_and_seeing.gif`
- `SUMV`, `SUMS`, and `SGSLOOP` in `YYYYMMDD.kcor.sgs.signal.gif`
- `RAV`, `RAS`, and `RAZR` in `YYYYMMDD.kcor.sgs.ra.gif`
- `DECV`, `DECS`, and `DECZR` in `YYYYMMDD.kcor.sgs.dec.gif`

I am currently using 3.0-10.0 for the range of `DIMV` and 0.0-8.0 for `SCINT`, but I need ranges for the rest of the values. I also need titles and y-axis titles.

**Comment by mgalloy** [comment]
I first draft is at:

    /hao/dawn/Data/KCor/raw.latest/20210801/p/20210801.kcor.sgs.*.gif

**Comment by jburkepile** [comment]
**Plot titles and y-axis labels:**
DEC PLOT:
DECV Title:   yyyy-mm-dd KCor DECV: Spar Guider System (SGS) Declination Error Signal
DECV y-axis:  SGS DEC Error Signal [Volts]

DECS Title: yyyy-mm-dd KCor DECS:  Spar Guider System (SGS) Declination Std Deviation
DECS y-axis:  SGS DEC Error Signal Std Dev [Volts]

DECZR Title: yyyy-mm-dd KCor DECZR: Spar Guider System (SGS) Declination Zero Point Offset
DECZR y-axis: SGS DECZR Zero Point Offset [Arcsec]

RA PLOT:
RAV Title:   yyyy-mm-dd KCor Spar Guider System (SGS) RAV Right Ascension Error Signal
RAV y-axis:  SGS RA Error Signal [Volts]

RAS Title: yyyy-mm-dd KCor Spar Guider System (SGS) RAS Right Ascension Std Deviation
RAS y-axis:  SGS RA Error Signal Std Dev [Volts]

RAZR Title: yyyy-mm-dd KCor Spar Guider System (SGS) RAZR Right Ascension Zero Point Offset
RAZR y-axis: SGS RAZR Zero Point Offset [Arcsec]

Seeing Plot: 
Change filename to yyyymmdd.kcor.sgs.sky_transmission_and_seeing.gif
DIMV Title:  yyy-mm-dd KCor Spar Guider System (SGS) DIMV Relative Sky Transmission Mean Signal
DIMV y-axis: SGS DIMV Relative Sky Transmission [Volts]

DIMS title: yyyy-mm-dd KCor Spar Guider System (SGS) DIMS Relative Sky Transmission Std Deviation
DIMS y-axis: SGS DIMS Relative Sky Transmission Std Deviation [Volts]

SCINT title: yyyy-mm-dd KCor Spar Guider System (SGS) Scintillation (Atmospheric Seeing) Estimate
SCINT y-axis:  SGS Scintillation (Seeing) Est. [Arcsec]

Signal Plot:
Add SGS LOOP plot so there will be 3 total plots in this file
SUMV Title: yyyy-mm-dd KCor Spar Guider System (SGS) SUMV Mean Sum Signal (Low Pass Filter of DIMV)
SUMV y-axis: SGS Mean Sum Signal [Volts]

SUMS Title: yyyy-mm-dd KCor Spar Guider System (SGS) SUMS Sum Signal Std. Deviation (Low Pass Filter of DIMS)
SUMS y-axis: SGS Sum Signal Std Deviation [Volts]

LOOP Title: yyyy-mm-dd KCor Spar Guider System (SGS) LOOP: Closed Loop Fraction 1=solar tracking, 0=drift
LOOP y-axis: SGS Closed Loop Fraction: 1 = solar tracking  0=drift

**Comment by mgalloy** [comment]
For an example of the new SGS plots, see:

    /hao/dawn/Data/KCor/raw.high-noise/20150718/p/*.sgs.*.gif
