### ISSUE TITLE
NEED new calibration epoch on Oct 18, 2021. Switched to using higher voltage SGS

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#253]
Ben switched to the SGS with higher voltage on Oct 18, 2021. Need new epochs in order to apply the right sky transmission correction. Must not use calibration across this epoch.

EPOCH BEGINS: 20211018 13:59:09 HST / 23:59:09 UT. 
Reason: SGS with higher voltage installed.

**Comment by mgalloy** [comment]
Redo cal files for the following days:

- [x] 20211019
- [ ] 20211020
- [ ] 20211021
- [ ] 20211023
- [ ] 20211025
- [ ] 20211026
- [ ] 20211031

Then reprocess the following days:

- [ ] 20211018
- [ ] 20211019
- [ ] 20211020
- [ ] 20211021
- [ ] 20211022
- [ ] 20211023
- [ ] 20211024
- [ ] 20211025
- [ ] 20211026
- [ ] 20211027
- [ ] 20211028
- [ ] 20211029
- [ ] 20211030
- [ ] 20211031
- [ ] 20211101

**Comment by jburkepile** [comment]
The pB values are now consistent for between data in this epoch and the previous epoch, i.e. the sky transmission correction is now using the appropriate SGS voltage for the epoch.  [JB]
I am closing this ticket.
