### ISSUE TITLE
Fix bad polarization start state in camera one only for data on 2021 Nov 01

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#256]
Camera 1 (only) is in wrong polarization state. Need to start at state 1 for camera 1 only

Start time:  20211101 09:18:37 HST (19:18:37 UT)

Stop time: 20211101 14:18:01 HST ( Nov 2 00:18:01 UT)

It is very odd when it is only one camera. We have seen this on rare occasion. It doesn't make sense to me; the beam splitter should make the states right for both or wrong for both. The only thing I can think of is camera 1 has the states shifted by one, i.e. its out of sync in how it is writing the states to the file. I don't see anything in the log about K-Cor when this happens.

Ben / Alfred may have a better explanation.

**Comment by mgalloy** [comment]
Fixed in f39a70427a022d6fba065159b0b13ff465aa38ed.

**Comment by mgalloy** [comment]
Duplicate and superseded by #280.
