### ISSUE TITLE
Update level 1 FITS header comment for 'OBJECT' keyword

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#258]
Update comment of Level 1 'OBJECT' keyword in FITS header to include  total intensity image. The old level 1 had 2 images. New Level 1 includes a 3rd image: i.e., the total intensity. 

Current level 1 header OBJECT keyword:

```
OBJECT  = 'K-Corona+sky; sky'  / img0=K-Corona pB + sky pB; img1=sky pB
```

The keyword and the value stay the same. Please

change comment to: 

```
/ img0=pB Corona+sky; img1=pB sky; img2=Tot Int
```

**Comment by mgalloy** [comment]
This was added in e8279f1ef79c4cbf53d9625a1b9ffead0e4d5e3f.

**Comment by mgalloy** [comment]
I think this is correct:

```
level1$ fitscat -r 20221007_205519_kcor_l1.fts.gz | grep OBJECT
OBJECT  = 'K-Corona+sky; sky'  / img0=pB Corona+sky; img1=pB sky; img2=Tot Int
```
