### ISSUE TITLE
Need to fix incorrect polarization sequence 20211119 camera 1 only

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#260]
Polarization sequences were taken in the wrong order for Camera 1 ONLY. Need to start at state = 1

Epoch starts:  20211119  at 10:08:48 (HST) / 20:08:48 (UT)

Epoch ends at: 20211119 at 11:17:05 (HST) / 21:17:05 (UT)  (I added a second on to the time of the last bad image)

**Comment by mgalloy** [comment]
Test in `raw.latest` in the temporary location for 20211119.

**Comment by mgalloy** [comment]
Joan verifies these are good now.
