### ISSUE TITLE
Copy older daily plots to /hao/acos/engineering for community use

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#265]
Copy 4 types of older files to `/hao/acos/engineeering/yyyy/mm/dd` so files can be accessed by the MLSO web page. 

- [x] 1.  daily pB radial intensity files. Filenames have format: `yyyymmdd.kcor.radial.intensity.gif`

- [x] 2. daily  pB vs time files and filenames for 4 different heights per day. Filename format: `yyyymmdd.kcor.mean-pb-1.11.gif`, `yyyymmdd.kcor.mean-pb-1.30.gif`, `yyyymmdd.kcor.mean-pb-1.50.gif`, `yyyymmdd.kcor.mean-pb-1.80.gif`

- [x] 3. Daily synoptic GIF and FITS files. Filename format: `yyyymmdd.kcor.28day.synoptic.r130.gif`, and FITS:
 `yyyyymmdd.kcor.28day.synoptic.r130.fts`

- [x] 4. Daily SGS plot of sky conditions. Filenames have CHANGED with time. Filename formats: 
       1. `yyyymmdd.sgs.eng.gif`      oldest filename. Last date used is Sept 14, 2021
       2. `yyyymmdd.kcor.sgs.seeing.gif`     Filename used Sept 15, 2021 thru Oct 18, 2021
       3. `yyyymmdd.kcor.sgs.sky_transmission_and_seeing.gif`        Latest version. Used in current pipeline
      
This must be done for:
- [x] all 2014
- [x] 20150101-20150110
- [x] 20150113-20210119
- [x] 20150301-20150321
- [x] 20150501-20150506
- [x] 20150701-20210717
- [x] 20150901-20150909
- [x] 20151101-20151115
- [x] 2019
- [x] 2020
- [x] 2021 until 20211213

The 2019, 2020, and 2021 dates are fixed as they are reprocessed with later pipeline versions.

**Comment by mgalloy** [comment]
This is done for all reprocessed data. Newly reprocessed, or processed, data now automatically distributes plots to the engineering directory.
