### ISSUE TITLE
Manually copy KCor daily plots to new engineering directories

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#272]
Manually copy recent KCor daily plots to `/hao/acos/engineering/yyyy/mm/dd`. 

**Copy all daily plots from Dec 18 2021 thru the present (Jan 7, 2022)**. These consist of:

- [x] 1. daily pB radial intensity files. Filenames have format: `yyyymmdd.kcor.radial.intensity.gif`

 - [x] 2. daily pB vs time files and filenames for 4 different heights per day. Filename format: `yyyymmdd.kcor.mean-pb- 1.11.gif`, `yyyymmdd.kcor.mean-pb-1.30.gif`, `yyyymmdd.kcor.mean-pb-1.50.gif`, `yyyymmdd.kcor.mean-pb-1.80.gif`

- [x]  3. Daily synoptic GIF and FITS files. Filename format: `yyyymmdd.kcor.28day.synoptic.r130.gif`, and FITS:
`yyyyymmdd.kcor.28day.synoptic.r130.fts`

- [x]  4. Daily SGS plot of sky conditions. Filenames have CHANGED with time. Filename formats:
1. `yyyymmdd.sgs.eng.gif` oldest filename. Last date used is Sept 14, 2021
2. `yyyymmdd.kcor.sgs.seeing.gif` Filename used Sept 15, 2021 thru Oct 18, 2021
3. `yyyymmdd.kcor.sgs.sky_transmission_and_seeing.gif` Latest version. Used in current pipeline

**In addition need to copy synoptic files over for Dec 14 through Dec 17, 2021**. For some reason these were not copied but the other daily plots were copied.
- [x]  Daily synoptic GIF and FITS files. Filename format: `yyyymmdd.kcor.28day.synoptic.r130.gif`, and FITS:
`yyyyymmdd.kcor.28day.synoptic.r130.fts`

**Comment by mgalloy** [comment]
The config file was copied over during the reprocessing in the second part of 2015 and the full 2016. We need to copy over the engineering files for the part of 2015 after the restart and the part of 2016 completed before now.
