### ISSUE TITLE
Fix bad polarization states found in 2020 reprocessing

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#274]
Add epochs for bad polarization start states on the following dates in 2020:

- [x] 20200816   Bad polarization states.  Use epoch:  07:07:50 to 12:22:40  [HST].  Start state = 3 for both cameras
- [x] 20200816 EPOCH: 07:07:50 to 12:22:40 HST  start state = [1,1]   I (Joan) incorrectly identified this data as start state = 3 (see checked item above). It is actually start state = 1. The current epochs.cfg file has the epocsh start and stop times correctly entered but they are commented out. Please uncomment these.

- [x] 20200828 EPOCH: 10:06:42 to 10:10:29 HST  Start state = [1,1]
- [x] 20200828 EPOCH:  10:10:30 to 10:11:15 HST  Start state = [2,2]
- [x] 20200828 EPOCH: 10:11:16 to 10:13:01  HST  Start state = [1,1]
- [x] 20200828 EPOCH:  10:13:02 to 10:26:57  HST  start state = [2,2]   
- [x] 20200828 EPOCH:  10:26:58  onward   start state = [0,0]

- [x] 20200920  EPOCH: 07:55:09 to 09:54:46  Start state = [1,1]. I (Joan) originally incorrectly identified this as start state = 3.

- [x] 20201009 EPOCH: 09:59:45 to 10:01:00  Use Camera 0 ONLY. start state = 0. Camera 1 polarization is too scrambled to be salvageable. 
- [x] 20201009 EPOCH: 10:01:01 to 10:01:45  Use both cameras. Start state = [0,1]
- [x] 20201009 EPOCH: 10:01:46 to 10:02:01  Use Camera 0 ONLY. start state = 0. Camera 1 polarization is too scrambled to be salvageable. 
- [x] 20201009 EPOCH: 10:02:02 to 10:45:54  Use both cameras. Start state = [0,1]      Data after this epoch reverts back to state [0,0].      FYI:  the original comment for this ticket was: ' bad polarization start state (pipeline recommendation: [0, 3]).'  I will check data to make sure 0,1 looks right after processing.

- [x] 20201020  EPOCH:  11:38:40 to 12:55:02  Start state = [1,1]. Please revise epoch file.

- [x] 20201024 EPOCH: 07:27:06 to 09:49:00  Start state = [1,1]. Please revise epoch file.

- [x] 20201128 EPOCH: 07:46:31 to 08:03:55  Start state = [1,1]. please revise epoch file.

**Comment by mgalloy** [comment]
Updates epochs in 9f608d1bdced206c989e759e03d8a5139abafcc7.
