### ISSUE TITLE
Fix extavg  images for days that have only a few (or one) images

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#279]
Some observing days have only one or a couple of images: Example: March 31, 2021
For these days the extavg pB image is solid black and the nrgf is solid white. Fix logic to check for number of good images. Continue to make extavg image even if there is only one frame. That can be noted in the gif annotation to call it to the users attention.

Joan needs to make a list of all days with this problem and give this list to Mike.

**Comment by jburkepile** [comment]
Reviewed all extended avg gif images for 2014 thru 2019 and found only 2 bad days that need to be reprocessed:
- [ ] 20160619 EPOCH: 09:10:57 HST  Don't process   Bad calibration: Spar RA problems 
- [ ] 20160619 EPOCH: 09:17:01 HST  Okay to process
- [ ] 20160619 EPOCH: 09:22:35 HST  Don't process    Bad calibration images
- [ ] 20160619 EPOCH: 09:37:15 HST  Okay to process

- [ ] 20180215  EPOCH: 08:03:34 HST  Don't process.  SGS Guider Error: Closing lens cover. Calpol is in beam: fits header is incorrect.
- [ ] 20180215  EPOCH: 08:57:30 HST  Okay to process.

**Comment by mgalloy** [comment]
Does this fix the extavg images? I can add this information to the epoch file and reprocess 20160619, 20160619, and 20180215. Will also produce new cal file for 20160619 and then reprocess dates that used the old bad one.

**Comment by jburkepile** [comment]
Mike:
Thanks for the comment. You need to DELETE the calibration file for 20160619. There are no good calibration images that day. I should have stated that explicitly
If any other days happened to use the 20160619 cal file then you are correct, they will need to be reprocessed.  Sorry it is more work for you.
Altogether this will fix all the bad images, including the extavg images.

**Comment by mgalloy** [comment]
I have deleted the cal file for 20160619 and checked the used cal files for 20160618 and 20160620 — neither used the bad cal file for 20160619. So all that needs to be done is reprocess 20160619.

**Comment by mgalloy** [comment]
See results in `raw.latest` for these two dates.

#### 20160619

- no calibration produced

#### 20180215

- no calibration produced because missing some cal angles missing: `required angles for full calibration data set not present`

**Comment by mgalloy** [comment]
@samaiyahfarid8 Can you verify the extended average is created for 20160619 and 20180215? We can then remove the testing tag and close this issue.
