### ISSUE TITLE
PDF version of observer logs for 2022 not on MLSO webpage

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#294]
This is not a high priority but needs to be fixed at some point. The pdf versions of the observer logs are not available for 2022. I believe the eod pipeline generates these, They should go in this directory:

    /hao/ftpd5/mlso/log/observer/2022

The text versions are in that directory and available to our users from the MLSO webpage. The PDF versions are available for years prior to 2022. Only 2022 is not available.

**Comment by mgalloy** [comment]
The PDF versions where created by a one-time process up to the end of 2021. I need to create a daily process to process them to a PDF on a time schedule.

**Comment by mgalloy** [comment]
I just created the PDFs for the logs up to yesterday (2022d096).

I also created a cronjob on dawn:

    5 0 * * * /home/mgalloy/bin/yesterday_olog2pdf.sh

that creates the PDF for the observer log for yesterday each morning.

**Comment by mgalloy** [comment]
I verified that the cronjob ran early this morning and produced a PDF for the observer log that came in last night for yesterday.

**Comment by jburkepile** [comment]
Thanks Mike!

**Comment by mgalloy** [comment]
This looks like the observer logs are being created now, but the webpage is not finding the observer logs when day-of-year is before 100, i.e., two digits. So April 9 is:

    mlso_observer_log.2022d099.pdf

not

    mlso_observer_log.2022d99.pdf

**Comment by mgalloy** [comment]
Permissions were correct on the PDF created last two nights.

**Comment by mgalloy** [comment]
@kolinski has fixed issue with website. I can download the PDF observer logs from the website now.

**Comment by jburkepile** [comment]
I have spot-checked multiple days and years and the pdfs are available from the webpage. The pdfs for DOY < 100 is also working for this year and previous years.

Thanks to Mike and Don for fixing these. Looks to me like this ticket can be closed.
