### ISSUE TITLE
Ability to retract CME alerts by observers

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#296]
Observers need to be able to retract an automated CME alert.

- [x] interface for observers that displays available CMEs and allows a particular CME to be retracted by adding it to the `YYYYMMDD.kcor.cme.toretract.txt` file in the `cme-list` directory — the list of CMEs that could be retracted can be found in `YYYYMMDD.kcor.cme.all.txt`
- [x] automated CME detection code needs to check "to retract" file on its data checking cadence, compare the entries to the "retracted" file, sending a retraction alert to the CCMC FTP servers if there is an entry in the "to retract" file that is not in the "retracted" file and adding that entry to the "retracted" file in that case

The format for the "to retract" file is:

    HH:MM:SS  [position angle with 2 decimal places] deg  [Free form comment with reason for retraction]

**Comment by bberkeyU** [comment]
If there are no CMEs for a day will the pipeline generate an empty YYYYMMDD.kcor.cme.all.txt or will this only exist if there are reported CME's?

Is the YYYYMMDD in HST (for the observing day) or UTC.  I assume HST, but I wanted to be sure.

**Comment by mgalloy** [comment]
There will only be a `YYYYMMDD.kcor.cme.all.txt` file if there were CMEs reported for that day.

The `YYYMMDD` in that filename is in HST — we call it the "observing day" so that everything for one day of observing is together. Where there are date/times, though, they are in UTC.

**Comment by bberkeyU** [comment]
That is what I was expecting, but didnt want to lean to hard on that assumption.

**Comment by mgalloy** [comment]
I successfully tested retracting a CME while running in the simulator on 20171006. I manually created the "toretract" file and it works now.

**Comment by mgalloy** [comment]
This hasn't run in production yet. @bberkeyU writes on November 23, 2022:

> I looks like I was writing things to: 
> 
> /export/data1/Data/KCor/cme-list.cme-test
> 
> I just changed to code to point to   /export/data1/Data/KCor/cme-list
