### ISSUE TITLE
Add PRODUCT keyword to pB images

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#323]
It should be:

    PRODUCT = 'pB      '           / Coronal polarization brightness

**Comment by mgalloy** [comment]
Is this only for level 2 files? What about level 1 files?

**Comment by jburkepile** [comment]
We can add a PRODUCT keyword to level 1 but it has to have a different value: 'Calibrated Intensity'. The level 1 contains 3 arrays; the first 2 are pB (sky+corona; sky) but the third array is total intensity NOT pB.

**Comment by mgalloy** [comment]
Can I use the following?

    PRODUCT = 'Calibrated intensity      ' / total intensity

**Comment by jburkepile** [comment]
MIke: Please add more to the comment to describe all three data rrays:

PRODUCT = 'Calibrated intensity      ' / pB corona+sky, pB sky, total intensity
