### ISSUE TITLE
Simulate CME detection for selected dates with expanded time range in .csv file in report

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#338]
1) Please change the CME alert code so that it reports 'tracking data' in the .csv file that was taken up to 30 minutes BEFORE the start of the CME   ( CME Tstart < 30 minutes )

If you can do #1 then Please rerun these 3 CMEs so we get more data points in the .csv file that comes with the CME report:

- [x] 20210507
- [x] 20220612
- [x] 20221031
- [x] 20211031

IF you CAN't do #1  please just rerun 20210507. Thanks very much!

**Comment by mgalloy** [comment]
Nothing was found in 20221031. Confirm time of event and attempt to determine why it was not found.

**Comment by jburkepile** [comment]
Mike ... I looked this up. I made a mistake ... This should have been 20211031. That was very careless of me. No need to pursue this for now.
