### ISSUE TITLE
Create synoptic maps at additional heights

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#345]
Heights to be determined.

**Comment by jburkepile** [comment]
Please create maps at these heights: all heights in solar radii
Height
- [ ] 1.11 - No other white light synoptic maps are this low in the corona
- [ ] 1.15
- [ ] 1.20
- [ ] 1.35
- [ ] 1.50
- [ ] 1.75
- [ ] 2.00
- [ ] 2.25
- [ ] 2.50
