### ISSUE TITLE
20210806 KCor wasn't properly processed

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#357]
20210806 K-Cor data processing did not successfully complete and the data did not make it to the web page.

The raw data are located on `/hao/corona3/Data/KCor/raw/20210806`.

When the mission is reprocessed on the next run, just want to verify that this day gets properly processed.

**Comment by mgalloy** [comment]
I am reprocessing this day now. It looks like the realtime process just died for some reason, and then the end-of-day never ran because the realtime process hadn't finished.

**Comment by jburkepile** [comment]
Thanks so much Mike!

**Comment by mgalloy** [comment]
It looks like it ran, but couldn't connect to the database for some reason. Re-running and it it connected to the database this time — at least at the beginning. Will monitor...

**Comment by mgalloy** [comment]
This is reprocessed and available on the website.
