### ISSUE TITLE
Update K-Cor header coordinate system to work with SunPy

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#360]
Add the following keywords to comply with SunPy and AstroPy:
- [x] DSUN_OBS = distance to the Sun from observer in meters. Get this from sun.pro with the 'DIST' keyword (or variable) and convert to meters. 1 AU = 149597870700 meters
- [x] HGLN_OBS = Stonyhurst heliographic longitude - the observer position. Set HGLN_OBS = 0 (zero) to indicate location to be at Earth
- [x] HGLT_OBS = heliosgraphic latitude - as seen by the observer. Set this equal to the B-angle which we already get from the ephemeris.
- [x]  OPTIONAL: set MJD-OBS and MJD-END corresponding to DATE-OBS and DATE-END (Modified Julian data which is JD - 2,400,000.5)
- [x] verify display of KCor image with SunPy Map (use 2022-10-02T20:27:32 for example image)

#### Questions

- [x] how does SunPy use `RSUN_REF`?
- [x] what is the correct value for `RSUN_REF` at KCor wavelengths (735 nm +/- some width)?

**Comment by mgalloy** [comment]
Here are the KCor and the AIA 193 images for 2022-10-02T20:27:32 displayed together:

![KCor and AIA 193 at 2022-10-02T20:27:32](https://github.com/NCAR/kcor-pipeline/assets/713524/0fbe13aa-f1e8-4546-aa28-bfa4a6087e86)

**Comment by jburkepile** [comment]
This looks fantastic Mike!   
I need to find out how to apply the 'nrgf' filter to the AIA images to view them off the limb. I will check with Sarah or Giuliana; I think they both know how to do that. That will fill in the narrow black ring between AIA and K-Cor that looks like a data gap. I would also like to have the AIA and K-Cor image times embedded in the upper left corner of the composite.  **You don't need to do these things.** This is something Ben can do and show the observers how to make changes, as part of the tasks the observers will work on while MLSO is closed.

**Comment by mgalloy** [comment]
The Jupyter notebook with the code to do this is in `tutorials/kcor-wcs.ipynb`.

**Comment by jburkepile** [comment]
Thanks! That is great to know.

**Comment by mgalloy** [comment]
By the way, there is still this warning:

```
INFO: Missing metadata for solar radius: assuming the standard radius of the photosphere. [sunpy.map.mapbase]
INFO: Missing metadata for solar radius: assuming the standard radius of the photosphere. [sunpy.map.mapbase]
```

I am not sure what is missing we have `DSUN_OBS`, `RSUN_OBS`, `R_SUN`, and `RSUN` FITS keywords. What is it looking for?

**Comment by mgalloy** [comment]
Looking at the SunPy code, it looks like it wants `RSUN_REF`, which is:

> RSUN_REF = radius of Sun in m, agreed upon standard, c. 6.96E8 but must be consistent with WAVELNTH keyword.

**Comment by mgalloy** [comment]
Still need correct value for `RSUN_REF`, but it seems to fix the SunPy Map warning.

**Comment by mgalloy** [comment]
UCoMP does not get this warning because we set `WAVELNG` instead of `WAVELNGTH`.

**Comment by mgalloy** [comment]
A fuller quote from the [SDO keyword documentation]:
```
From SDO attitude and orbit information:
   ...
   DSUN_OBS distance to Sun center from spacecraft in m, c. 1.5E11.
   RSUN_REF = radius of Sun in m, agreed upon standard, c. 6.96E8 but must be consistent with WAVELNTH keyword.

For AIA:
   ...
   IM_SCALE is the predefined AIA plate scale in arc-seconds per pixel.
   R_SUN is computed from DSUN_OBS, RSUN_REF, and IM_SCALE.

For HMI:
   R_SUN is computed from the same fit to each image.
   IM_SCALE is computed from R_SUN and DSUN_OBS and RSUN_REF.
```

[SDO keyword documentation]: http://jsoc.stanford.edu/doc/keywords/JSOC_Keywords_for_metadata.pdf

**Comment by mgalloy** [comment]
`RSUN_REF` could be computed with:

``` IDL
radius = (radius_0 + radius_1) / 2.0
dsun_obs = dist_au * au_to_meters
rsun_ref = dsun_obs * tan(run->epoch('plate_scale') * radius / 60.0 / 60.0 * !dtor)
```

The values I get from the files on 20221002 are about 7.35E8 (I am using 6.96E8 now).

**Comment by mgalloy** [comment]
`RSUN_REF` can be calculated with the arcsec/mm value found using the size of the occulter (in mm) and the focal length of the instrument using optical formulas similar to UCoMP's calculation.

**Comment by jburkepile** [comment]
Value of RSUN_REF at KCor center wavelength 735 nm = 696182 km. 
_Reference used:  'Solar radius determined from PICARD/SODISM observations and extremely weak wavelength dependence in the visible and the near-infrared' by Meftah et al. 2018;  https://doi.org/10.1051/0004-6361/201732159_
We should include that reference in a comment that has the DOI.

The solar diameter varies from 696179 to 696185 km over the K-Cor wavelength range of 720 to 750 nm. The uncertainty in the RSUN_REF cited above is likely larger than +/- 3 km since the PICARD measurements were not made exactly at the K-Cor wavelengths. I interpolated the PICARD data to extract the value of the solar diameter over the K-Cor wavelengths. 

NOTE: The RSUN_REF value is important for solar datasets that view the Sun's disk, such as AIA and ChroMag. The platescale of these datasets can be checked using RSUN_REF.  That doesn't hold for coronagraphs that block the disk with an occulter. The physical size of the occulter needs to be used. Our occulter names in the 'OCCLTRID' keyword contain the size of the occulter in arcseconds and should be used to check platescale. Do you think it is worth putting a comment in the header about this for our users?

**Comment by mgalloy** [comment]
There are new files in `raw.latest/20221007`:

``` bash
level2$ fitscat -r 20221007_173900_kcor_l2.fts | grep RSUN_REF
RSUN_REF=          6.96182E+08 / [m] solar rad. doi:10.1051/0004-6361/201732159
```
