### ISSUE TITLE
Names for new occulters

### ISSUE THREAD

**Issue by bberkeyU** [NCAR/kcor-pipeline#368]
The new occulters have arrived. In the drawings, these occulters are named T1, T2, T3.  

What names should we use for the fits headers? During eclipse prep/eclipse obs, I think we are going to use the T2 occulter so we need to agree on the names and get them into the kcor `epochs.spec.cfg` file.

Following our old scheme T2 might be OC-T2 but this doesn't give a data user any concept of the diameter in arcseconds.

There is a new issue #369 that creates a new naming scheme, consistent with this naming, for the older occulters.

#### Tasks

- [x] create epoch entries for occulter sizes in mm and arcseconds
- [x] change comment for occulter in the level 1 and 2

**Comment by jburkepile** [comment]
The original occulter names had the diameter in arcsec based on the effective focal length of the Jenoptik lens. I put a Jira ticket in last month asking the IG to measure the effective focal length of the Optimax lens currently in K-Cor. We don't have that yet. 
I suggest we go with the physical diameter of the occulters in mm. I have taken the average of the vendor (OPTX) and the DFS diameter measurements and converted them to mm to get:
T1: 19.950 +/- 0.009  [mm]
T2: 19.702 +/- 0.005  [mm]
T3: 19.486 +/- 0.005  [mm]

I suggest we name them by their physical sizes and then add a keyword for the effective focal length (EFL) of the objective lens we are using.
New occulter names    and please change the comment:
OC-T1-19.950    / ID occulter,  size of radius in mm
OC-T2-19.702    / ID occulter,  size of radius in mm
OC-T3-19.486    /  ID occulter, size of radius in mm

Mike - Are you okay with this change in the name? 
We can later add a keyword for the effective focal length (EFL) of the objective lens we are using once we get the Optimax EFL from the IG.

**Comment by mgalloy** [comment]
For the pipeline, as long as the first 8 characters are unique amongst the possible occulted names, the names don't matter.

**Comment by mgalloy** [comment]
Before we implement #369, I need sizes in arcseconds for the new occulters (assuming the current objective lens).

**Comment by bberkeyU** [comment]
Changing of the Kcor header comments is harder than ucomp; because they are hard coded.  I would like to delay changing the comment until we confirm we will only be using the new occulter or until we get more stable power so I can upgrade the whole fits keyword system to be scribable.

**Comment by jburkepile** [comment]
How about reporting:
T1 radius in arcsec = 1019.32 +/- 0.36 arcsec
T2 radius in arcsec = 1006.65 +/- 0.16 arcsec
T3 radius in arcsec = 995.61 +/- 0.16 arcsec

**Comment by mgalloy** [comment]
The pipeline is now using the following comments:

| Occulter | OCCLTRID comment |
| -------- | ---------------- |
| OC-991.6 | ID occulter, diameter in arcsec |
| OC-1018.9 | ID occulter, diameter in arcsec |
| OC-1006.9 | ID occulter, diameter in arcsec |
| OC-1 | ID occulter |
| OC-1017.0 | ID occulter, diameter in arcsec |
| OC-T1-19.950 | ID occulter, diameter in mm |
| OC-T2-19.702 | ID occulter, diameter in mm |
| OC-T3-19.486 | ID occulter, diameter in mm |
