### ISSUE TITLE
Process end of day for June 12, 2016

### ISSUE THREAD

**Issue by samaiyahfarid8** [NCAR/kcor-pipeline#373]
Note: All plots are missing on website. Only real-time data products are available. e.g. no plots indicating end of day process did not run.
Procedure: Check end of day logs and determine if data was created.

Process/reprocess the given date(s).

#### Tasks

- [x] reprocess dates (June 12, 2016)
- [ ] make sure the appropriate synoptic maps appear on the website

**Comment by mgalloy** [comment]
I had to retrieve the level 0 from the campaign storage archive. For some reason there were only 113 files in the t1/t2 logs, but there are 691 level 0 files, so I generated new t1/t2 logs.

**Comment by jburkepile** [comment]
Thanks Mike for finding that problem and ensuring that all the data get processed. That was probably due to the problems with Kodiak that day - it was down for part of the day.

**Comment by mgalloy** [comment]
The day has been reprocessed. Please verify.

**Comment by jburkepile** [comment]
Dear Samaiyah:

Mike has reprocessed the data for June 12 2016. He has asked that we verify
that  it worked. We need to check the web page to make sure all the data
are on the web page.  If the data are there you can add a comment to the
github ticket that the reprocessing worked.

Thanks!
Joan

**Comment by samaiyahfarid8** [comment]
Reprocessing has created the missing end-of-day plots. The only remaining missing plot is the synoptic image, which is created through different process. The synoptic image should be generated at the next calibration reprocessing run.

**Comment by mgalloy** [comment]
Synoptic maps were made for 20160612, but I think we have changed the heights they are produced at since we last took data or reprocessed a date. I think the website might be looking for a height that we don't produce anymore? The below are present in the synoptic maps directory. Note that the old height is actually present (1.3 R_sun), but is not present in the database? In any case, the reprocessing code needs to delete old synoptic maps.

``` shell
06$ ll 20160612*
-rw-rw-r--. 1 mgalloy cordyn  82K Apr 16 02:13 20160612.kcor.28day.synoptic.r111.fts
-rw-rw-r--. 1 mgalloy cordyn 195K Apr 16 02:13 20160612.kcor.28day.synoptic.r111.gif
-rw-rw-r--. 1 mgalloy cordyn  82K Apr 16 02:13 20160612.kcor.28day.synoptic.r115.fts
-rw-rw-r--. 1 mgalloy cordyn  25K Apr 16 02:13 20160612.kcor.28day.synoptic.r115.gif
-rw-rw-r--. 1 mgalloy cordyn  82K Apr 16 02:13 20160612.kcor.28day.synoptic.r120.fts
-rw-rw-r--. 1 mgalloy cordyn  24K Apr 16 02:13 20160612.kcor.28day.synoptic.r120.gif
-rw-rw-r--. 1 mgalloy cordyn  82K Mar  7  2022 20160612.kcor.28day.synoptic.r130.fts
-rw-rw-r--. 1 mgalloy cordyn 201K Mar  7  2022 20160612.kcor.28day.synoptic.r130.gif
-rw-rw-r--. 1 mgalloy cordyn  82K Apr 16 02:13 20160612.kcor.28day.synoptic.r135.fts
-rw-rw-r--. 1 mgalloy cordyn 209K Apr 16 02:13 20160612.kcor.28day.synoptic.r135.gif
-rw-rw-r--. 1 mgalloy cordyn  82K Apr 16 02:13 20160612.kcor.28day.synoptic.r150.fts
-rw-rw-r--. 1 mgalloy cordyn  23K Apr 16 02:13 20160612.kcor.28day.synoptic.r150.gif
-rw-rw-r--. 1 mgalloy cordyn  82K Apr 16 02:13 20160612.kcor.28day.synoptic.r175.fts
-rw-rw-r--. 1 mgalloy cordyn 195K Apr 16 02:13 20160612.kcor.28day.synoptic.r175.gif
-rw-rw-r--. 1 mgalloy cordyn  82K Apr 16 02:13 20160612.kcor.28day.synoptic.r200.fts
-rw-rw-r--. 1 mgalloy cordyn  21K Apr 16 02:13 20160612.kcor.28day.synoptic.r200.gif
-rw-rw-r--. 1 mgalloy cordyn  82K Apr 16 02:13 20160612.kcor.28day.synoptic.r225.fts
-rw-rw-r--. 1 mgalloy cordyn  19K Apr 16 02:13 20160612.kcor.28day.synoptic.r225.gif
-rw-rw-r--. 1 mgalloy cordyn  82K Apr 16 02:13 20160612.kcor.28day.synoptic.r250.fts
-rw-rw-r--. 1 mgalloy cordyn  16K Apr 16 02:13 20160612.kcor.28day.synoptic.r250.gif
```

**Comment by mgalloy** [comment]
I've added a new issue for failure to remove old synoptic maps #374.

**Comment by jburkepile** [comment]
Thanks so much Samaiyah!!

**Comment by mgalloy** [comment]
The pipeline is now using the following comments:

| Occulter | OCCLTRID comment |
| -------- | ---------------- |
| OC-991.6 | ID occulter, diameter in arcsec |
| OC-1018.9 | ID occulter, diameter in arcsec |
| OC-1006.9 | ID occulter, diameter in arcsec |
| OC-1 | ID occulter |
| OC-1017.0 | ID occulter, diameter in arcsec |
| OC-T1-19.950 | ID occulter, diameter in mm |
| OC-T2-19.702 | ID occulter, diameter in mm |
| OC-T3-19.486 | ID occulter, diameter in mm |

**Comment by mgalloy** [comment]
The preferred synoptic map for the website is `20160612.kcor.28day.synoptic.r135.gif`.

**Comment by mgalloy** [comment]
Website is now showing the synoptic maps. It is getting them from the engineering directory, not the synmaps directory.
