### ISSUE TITLE
Change BUNIT value to specify mean solar disk brightness

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#377]
The K-Cor (and UCoMP) headers do not specify the units of solar disk brightness. K-Cor is in units of mean solar disk brightness [UCoMP is in units of solar disk center brightness]. We will use the BUNIT keyword standard to match the Metis coronagraph headers. 

Please change the BUNIT keyword in the K-Cor headers to:
 - [x] BUNIT = 'Mean Solar Brightness'  /  [B/Bsun] Mean solar disk brightness

**Comment by mgalloy** [comment]
The comment is getting truncated:

```
BUNIT   = 'Mean Solar Brightness' / [B/Bsun] units of entire solar disk brightne
```

**Comment by jburkepile** [comment]
For reference here are BUNIT values from other coronagraphs:

PUNCH BUNIT value is 'Mean Solar Brightness'   the comment is 'Unit of observation'    
LASCO BUNIT value is MSB" and the comment is:   'Mean solar brightness'
Metis BUNIT value is 'MSB' and the comment is 'Units of Physical value'
STEREO COR1 BUNIT value is 'MSB'
SMM BUNIT is 'Bsun' and the comment is 'Brightness relative to the solar disk'     Bsun is the brightness of the solar disk - I believe this is the mean disk brightness. I am trying to track down a reference.
