### ISSUE TITLE
Rename umk4 and qmk4 variables in KCor pipeline

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#401]
The KCor variables 'umk4' and 'qmk4' are not descriptive of what these variables are to the general user. Change the variable names and add an extended comment to explain to users how sky polarization is removed from the data.

Change 'umk4'  to 'corona_plus_sky'
Change 'qmk4'  to 'sky_polarization'
Add a comment to line 699 of the kcor_l1.pro program as given below.

These variables appear in these 3 programs:  
- [x] Change variables in kcor_l1.pro    
- [x] Change variables in kcor_l2.pro   
- [x] Change variables in kcor_sine2theta_method.pro
- [x] Add this to the comment on line 699 of kcor_l1.pro;    current comment: 'polar coordinates'.   Add: "The k-corona polarization is tangent to the solar limb. The corona_plus_sky variable isolates the coronal signal but still includes sky polarization.   The sky_polarization variable contains no coronal signal and is used to remove sky polarization from the coronal image. The sky polarization is removed in level 2 processing."

**Comment by mgalloy** [comment]
I ran this on 20240330 in `raw.latest` in the new location and seemed to be fine, i.e., there were no error messages or crashes.

**Comment by jburkepile** [comment]
Thanks for getting this done Mike. I verified that the code changes produced the identical calibrated pB values. 
This ticket can be closed.
