### ISSUE TITLE
Improve FAIR assessment of data

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#405]
Our current score is 4% at the [F-UJI FAIR assessment tool] (and [paper]).

[F-UJI FAIR assessment tool]: https://www.f-uji.net/index.php?action=test
[paper]: https://zenodo.org/records/6461229

**Comment by jburkepile** [comment]
I took a quick look at the FAIR info. I think it is good to point to the home page. It is much more informative and the data access are clearly visible on the page. Why is it a lot of work to point to the MLSO homepage? You know much more about this than I do. 
We can revisit the DASH entry when we are both back and see what else we can add.
Thanks!

**Comment by mgalloy** [comment]
It's not more work to point to either page. It would be more work to get our FAIR Assessment for our webpage (currently 4%) to be better than the DASH page for KCor (currently 75%).
