### ISSUE TITLE
Process 20170531 with updated distortion coefficients

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#406]
Use the updated distortion coefficients in `dist_coeff_20170522_205121_ben` to process 20170531.

Needed for #367 and, finally, #364.

**Comment by mgalloy** [comment]
Results are appearing for the test run. It is in `raw.new-dist` on our main data server.

**Comment by jburkepile** [comment]
I have looked at the level 2 header for 20170531_165350_kcor_l2_pb.fts
The distortion corrected occulter radii for the cameras are:
OLD (CURRENT) distortion:   cam0 = 180.570   cam1 = 180.160  delta = 0.41 pixels
NEW (BEN) distortion:           cam0 = 180.32     cam1 = 179.92    delta = 0.40 pixels

No improvement in reducing the difference in the apparent occulter sizes between cameras.

**Comment by mgalloy** [comment]
New results for `dist_coeff_20170522_205121_dark-correct_rescale.sav` are in `raw.new-dist-2`.
