### ISSUE TITLE
Check skypol_bias = 0.010

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#55]
Review data. This is very high. Should be between <= .004.

**Comment by mgalloy** [comment]
This is just a value in the epoch file.

**Comment by mgalloy** [comment]
We will do some runs with no `skypol_bias` to determine how bad the data looks.

**Comment by mgalloy** [comment]
Compared KCor data to PolarCam eclipse data with and without bias and biased images were a better fit overall.

**Comment by mgalloy** [comment]
@jburkepile Is this issue done? We don't have a bias now, correct?

**Comment by mgalloy** [comment]
Yes, in `epochs.spec.cfg`:

```
skypol_bias                     : type=float, default=0.0
```

**Comment by jburkepile** [comment]
Leave the sky polarization bias set to zero.
