### ISSUE TITLE
Improve engineering data

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#75]
1. The range of the `SGSDIMV` value changed at least 3 times in 2018. Need to change daily plotting code to accommodate the full range of the values. Its currently fixed at `yrange = [5.5, 7.5]`. May need a range of 3 to 9.  (CHECK)

2. View other engineering data in database and make final changes before data are reprocessed.

**Comment by mgalloy** [comment]
Add a `kcor_raw` table, that would have the following fields:

    raw_id         INT (10) AUTO_INCREMENT PRIMARY KEY, 
    file_name      CHAR (40) NOT NULL, 
    date_obs       DATETIME NOT NULL, 
    date_end       DATETIME NOT NULL,
    obs_day        MEDIUMINT (5) NOT NULL,
    level          TINYINT (2) NOT NULL, 
    quality_id     TINYINT (2) NOT NULL,
    mean_int_img0  FLOAT (14, 7),
    mean_int_img1  FLOAT (14, 7),
    mean_int_img2  FLOAT (14, 7),
    mean_int_img3  FLOAT (14, 7),
    mean_int_img4  FLOAT (14, 7),
    mean_int_img5  FLOAT (14, 7),
    mean_int_img6  FLOAT (14, 7),
    mean_int_img7  FLOAT (14, 7),
    median_int_img0  FLOAT (14, 7),
    median_int_img1  FLOAT (14, 7),
    median_int_img2  FLOAT (14, 7),
    median_int_img3  FLOAT (14, 7),
    median_int_img4  FLOAT (14, 7),
    median_int_img5  FLOAT (14, 7),
    median_int_img6  FLOAT (14, 7),
    median_int_img7  FLOAT (14, 7),

**Comment by mgalloy** [comment]
bbba38db372fc67545403d69d62bdef55bf32a70 has a draft of populating `kcor_raw`.
