### ISSUE TITLE
Masking

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#81]
The mask is now 5 pixels around the occulter, it should be possible to make this smaller.

- [x] Change mask from 5 pixels to 2 pixels
- [x] Save a completely unmasked image every 60 images, i.e., about 15 minutes ("reprocess" at end of day with a `/NOMASK` flag to `KCOR_L1` to produce GIF and FITS) in a `nomask` subdirectory of the `save` directory

**Comment by jburkepile** [comment]
Currently changed mask size in inner FOV from occulter size + 5 pixels to occulter size + zero pixels.

**Comment by mgalloy** [comment]
d75fe5b628006103defbe49a83387e918dbeac01 changes over masking from 2 pixels to 3 pixels.
