### ISSUE TITLE
Interpolate bad values in camera correction

### ISSUE THREAD

**Issue by mgalloy** [NCAR/kcor-pipeline#87]
To do:

- [x] find the bad pixels in a camera correction
- [x] interpolate values for the bad pixels from surrounding pixels
- [x] produce alternate set of camera correction files with fix baked in

Note: the camera correction files might already have a mask that already identifies the bad pixels in the camera correction.

**Comment by mgalloy** [comment]
Using bad pixel mask from the camera correction file, but also checking for < -1.0 or > 1.0 in the x^4 coefficient to add more bad pixels.

**Comment by jburkepile** [comment]
Thanks mike! I will be around tomorrow. Hope you have a good night

**Comment by mgalloy** [comment]
Caching all camera correction parameters including a better bad pixel mask in a `.cache` directory inside the camera correction directory.

**Comment by mgalloy** [comment]
Released in 1.5.11.
