### ISSUE TITLE
Carrington rotation number

### ISSUE THREAD

**Issue by detoma** [NCAR/kcor-pipeline#94]
I noticed `sun.pro` is not always giving the correct `CAR_ROT`. There are cases when the L0 is close to the boundary between 0 and 360 when the carrington rotation number is incorrect.

I suggest using the solarsoft routine `tim2carr.pro` to get Carrington rotation number and L0 before we reprocess.

**Comment by mgalloy** [comment]
@detoma Is there a particular day that you noticed has a problem that I could test on?

**Comment by mgalloy** [comment]
Verified for 20190116. The first image for CR 2213 is 19:55:10 UT, but the tables say 19:48 UT. So off about 7 minutes, but better than 8.5 hours from using `SUN`.
